spring:
  application:
    name: Railway
  datasource:
    url: jdbc:postgresql://localhost:5432/railway
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jjwt:
  token:
    key:
      secret: O4xoGCVmFqHnkkbcOkqnD/yB2V/W8dpQpFXq981jDOt4dnyB0Ya+v1DpYNYh8N+UXSMfPCC9wCglXyjAgEKsRQ==
    time:
      expiration: 3600000
springdoc:
  swagger-ui:
    csrf:
      enabled: true
    path: /swagger
